export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer'
export {default as About} from './About/About'
export {default as Skill} from './Skills/Skill'
export {default as Testimonial} from './Testimonial/Testimonial'
export {default as Works} from './Works/Works'
